"""Slack notification tool with approval mechanism."""

from __future__ import annotations

from typing import Literal

from agents import function_tool
from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError

from cloudwatch_triage_agent.config import get_config

# Global approval state - in production, use proper state management
_pending_messages: dict[str, dict] = {}


def _get_slack_client() -> WebClient:
    """Get a Slack WebClient."""
    config = get_config()
    return WebClient(token=config.slack.bot_token)


def _severity_to_color(severity: str) -> str:
    """Convert severity to Slack attachment color."""
    colors = {
        "critical": "#dc3545",  # Red
        "warning": "#ffc107",   # Yellow
        "info": "#17a2b8",      # Blue
    }
    return colors.get(severity, "#6c757d")  # Gray default


def _build_slack_blocks(
    title: str,
    body: str,
    severity: str,
    cause_candidates: list[dict],
    investigation_link: str | None = None,
) -> tuple[list[dict], list[dict]]:
    """Build Slack blocks and attachments for the message."""
    blocks = [
        {
            "type": "header",
            "text": {
                "type": "plain_text",
                "text": f"🔍 {title}",
                "emoji": True,
            },
        },
        {
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": body,
            },
        },
        {"type": "divider"},
    ]

    # Add cause candidates
    if cause_candidates:
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": "*Root Cause Candidates:*",
            },
        })

        for candidate in cause_candidates:
            rank = candidate.get("rank", "?")
            candidate_title = candidate.get("title", "Unknown")
            description = candidate.get("description", "")
            confidence = candidate.get("confidence", "unknown")
            evidence = candidate.get("evidence", [])

            confidence_emoji = {"high": "🔴", "medium": "🟡", "low": "🟢"}.get(confidence, "⚪")

            evidence_text = "\n".join(f"  • {e}" for e in evidence[:3]) if evidence else "No evidence"

            blocks.append({
                "type": "section",
                "text": {
                    "type": "mrkdwn",
                    "text": f"*#{rank} {candidate_title}* {confidence_emoji} ({confidence} confidence)\n{description}\n\n_Evidence:_\n{evidence_text}",
                },
            })

    # Add investigation link if provided
    if investigation_link:
        blocks.append({"type": "divider"})
        blocks.append({
            "type": "section",
            "text": {
                "type": "mrkdwn",
                "text": f"<{investigation_link}|📊 View detailed investigation in CloudWatch>",
            },
        })

    # Add footer
    blocks.append({
        "type": "context",
        "elements": [
            {
                "type": "mrkdwn",
                "text": "Generated by CloudWatch Triage Agent • Please verify findings before taking action",
            }
        ],
    })

    # Create attachment for color sidebar
    attachments = [
        {
            "color": _severity_to_color(severity),
            "blocks": blocks,
        }
    ]

    return [], attachments  # Return empty blocks, use attachments for color


@function_tool
def post_to_slack(
    title: str,
    body: str,
    severity: Literal["critical", "warning", "info"],
    cause_candidates: list[dict],
    investigation_link: str | None = None,
    channel_override: str | None = None,
    require_approval: bool = True,
) -> dict:
    """Post an incident triage summary to Slack.

    IMPORTANT: This action requires human approval before execution when
    require_approval is True. The message will be queued and must be
    approved via approve_slack_message() before being sent.

    Args:
        title: Message title/header (e.g., "API Service Incident Triage - 2024-01-15")
        body: Main message body in Slack markdown format. Include:
              - Incident summary
              - Affected service and environment
              - Time range of investigation
        severity: Severity level for color coding:
                 - 'critical': Red sidebar (service down/major impact)
                 - 'warning': Yellow sidebar (degraded performance)
                 - 'info': Blue sidebar (investigation complete, low impact)
        cause_candidates: List of cause candidate dictionaries, each containing:
                         - rank: int (1-3)
                         - title: str
                         - description: str
                         - confidence: str ('high', 'medium', 'low')
                         - evidence: list[str]
        investigation_link: Optional link to CloudWatch console or dashboard
        channel_override: Override the default Slack channel (optional)
        require_approval: If True (default), message is queued for approval.
                         If False, message is sent immediately (use with caution).

    Returns:
        Dictionary containing:
        - status: 'pending_approval', 'sent', or 'failed'
        - message_id: Unique ID for the pending message (if pending)
        - preview: Preview of the message to be sent
        - channel: Target Slack channel
        - error: Error message if failed
    """
    config = get_config()
    channel = channel_override or config.slack.channel_id

    if not channel:
        return {
            "status": "failed",
            "error": "No Slack channel configured. Set SLACK_CHANNEL_ID or provide channel_override.",
        }

    if not config.slack.bot_token:
        return {
            "status": "failed",
            "error": "No Slack bot token configured. Set SLACK_BOT_TOKEN.",
        }

    # Build the message
    blocks, attachments = _build_slack_blocks(
        title=title,
        body=body,
        severity=severity,
        cause_candidates=cause_candidates,
        investigation_link=investigation_link,
    )

    message_data = {
        "channel": channel,
        "text": f"🔍 {title}",  # Fallback text for notifications
        "blocks": blocks,
        "attachments": attachments,
    }

    # Generate preview for approval
    preview = f"""
=== Slack Message Preview ===
Channel: {channel}
Severity: {severity}
Title: {title}

Body:
{body}

Cause Candidates:
"""
    for candidate in cause_candidates:
        preview += f"  #{candidate.get('rank', '?')} {candidate.get('title', 'Unknown')} ({candidate.get('confidence', 'unknown')} confidence)\n"

    if investigation_link:
        preview += f"\nInvestigation Link: {investigation_link}"

    if require_approval:
        # Queue message for approval
        import uuid

        message_id = str(uuid.uuid4())[:8]
        _pending_messages[message_id] = message_data

        return {
            "status": "pending_approval",
            "message_id": message_id,
            "preview": preview,
            "channel": channel,
            "approval_instruction": f"To send this message, call approve_slack_message(message_id='{message_id}')",
        }

    # Send immediately if approval not required
    try:
        client = _get_slack_client()
        response = client.chat_postMessage(**message_data)

        return {
            "status": "sent",
            "channel": channel,
            "timestamp": response.get("ts"),
            "preview": preview,
        }

    except SlackApiError as e:
        return {
            "status": "failed",
            "error": f"Slack API error: {e.response['error']}",
            "preview": preview,
        }
    except Exception as e:
        return {
            "status": "failed",
            "error": f"Failed to send message: {str(e)}",
            "preview": preview,
        }


@function_tool
def approve_slack_message(message_id: str) -> dict:
    """Approve and send a pending Slack message.

    This function sends a message that was previously queued by post_to_slack()
    with require_approval=True.

    Args:
        message_id: The message ID returned by post_to_slack()

    Returns:
        Dictionary containing:
        - status: 'sent' or 'failed'
        - channel: Slack channel the message was sent to
        - timestamp: Slack message timestamp
        - error: Error message if failed
    """
    if message_id not in _pending_messages:
        return {
            "status": "failed",
            "error": f"Message ID '{message_id}' not found. It may have expired or already been sent.",
        }

    message_data = _pending_messages.pop(message_id)

    try:
        client = _get_slack_client()
        response = client.chat_postMessage(**message_data)

        return {
            "status": "sent",
            "channel": message_data["channel"],
            "timestamp": response.get("ts"),
        }

    except SlackApiError as e:
        # Put message back in queue on failure
        _pending_messages[message_id] = message_data
        return {
            "status": "failed",
            "error": f"Slack API error: {e.response['error']}",
            "message_id": message_id,
        }
    except Exception as e:
        _pending_messages[message_id] = message_data
        return {
            "status": "failed",
            "error": f"Failed to send message: {str(e)}",
            "message_id": message_id,
        }


@function_tool
def get_pending_slack_messages() -> dict:
    """Get list of pending Slack messages awaiting approval.

    Returns:
        Dictionary containing:
        - pending_count: Number of messages pending approval
        - messages: List of pending message IDs and their channels
    """
    messages = [
        {"message_id": msg_id, "channel": data["channel"]}
        for msg_id, data in _pending_messages.items()
    ]

    return {
        "pending_count": len(messages),
        "messages": messages,
    }
